### ISSUE TITLE
Deobfuscator Error

### ISSUE THREAD

**Issue by Holo795** [Ikos3k/JavaDeobfuscator#1]
Hello, when I test your program I have this error :

`LocalVariableRemoverTransformer running...
AnnotationRemoveTransformer running...
FieldNameTransformer running...
ClassNameTransformer running...
FixAccessTransformer running...
SuperBlaubeere27StringTransformer running...
Exception in thread "main" java.lang.ClassCastException: class org.objectweb.asm.Type cannot be cast to class java.lang.String (org.objectweb.asm.Type is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
        at me.ANONIMUS.deobf.transformer.impl.string.SuperBlaubeere27StringTransformer.visit(SuperBlaubeere27StringTransformer.java:32)
        at me.ANONIMUS.deobf.Deobfuscator.lambda$run$0(Deobfuscator.java:70)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at me.ANONIMUS.deobf.Deobfuscator.run(Deobfuscator.java:67)
        at me.ANONIMUS.deobf.DeobfuscatorInitializer.main(DeobfuscatorInitializer.java:19)`

If someone can help me :)

**Comment by narumii** [comment]
What are you excepting from skidded deobfuscator lol? xd
Also no one can help you, he fucked up transformers
