### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JonnyOnline** [Ikos3k/JavaDeobfuscator#3]
When the Deobfucator reaches the Superblaubeere24StringTransformer, it gives an exception in Main that org.objectweb.asm.Type cannot be cast to Java.lang.String

**Comment by Ikos3k** [comment]
Can you send full Exception message from console?

**Comment by JonnyOnline** [comment]
$ java -jar JavaDeobfuscator.jar Test.jar
[INFO] Successful loaded Test.jar [3478 class] [4032 files]

LocalVariableRemoverTransformer running...
AnnotationRemoveTransformer running...
FieldNameTransformer running...
ClassNameTransformer running...
FixAccessTransformer running...
SuperBlaubeere27StringTransformer running...
Exception in thread "main" java.lang.ClassCastException: org.objectweb.asm.Type cannot be cast to java.lang.String
        at me.ANONIMUS.deobf.transformer.impl.string.SuperBlaubeere27StringTransformer.visit(SuperBlaubeere27StringTransformer.java:32)
        at me.ANONIMUS.deobf.Deobfuscator.lambda$run$0(Deobfuscator.java:70)
        at java.util.ArrayList.forEach(Unknown Source)
        at me.ANONIMUS.deobf.Deobfuscator.run(Deobfuscator.java:67)
        at me.ANONIMUS.deobf.DeobfuscatorInitializer.main(DeobfuscatorInitializer.java:19)

**Comment by JonnyOnline** [comment]
Im on win10 21H1 64bit

**Comment by JonnyOnline** [comment]
Hello?

**Comment by JonnyOnline** [comment]
Please

**Comment by JonnyOnline** [comment]
Day 468854235678 of waiting for a reply

**Comment by JonnyOnline** [comment]
Day -2 of waiting for a reply

**Comment by cherabear4** [comment]
bro just use a different deobfuscator lmao

**Comment by JonnyOnline** [comment]
No
